# This file must be in the root directory of your GitHub repository.
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root